name: Nightly
on:
  schedule:
    - cron: "23 0 * * *"
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assembleFossRelease

      - uses: r0adkll/sign-android-release@v1
        id: foss
        with:
          releaseDirectory: app/build/outputs/apk/foss/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: nightly
          prerelease: true
          title: "Nightly Release"
          files: |
            ${{ steps.foss.outputs.signedReleaseFile }}
